name: EHML2024
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - jupyter
  - jupyterlab
  - seaborn
  - pip
  - ipywidgets
  - scikit-learn
  - pip:
    - openpyxl