name: EHML
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - jupyter
  - jupyterlab
  - seaborn
  - pip
  - ipywidgets
  - scikit-learn
  - torch
  - pip:
    - torch
    - torchvision
    - transformers
    - pytorch-lightning
    - 'lightning-flash[tabular,text,image]'
    - plotly
    - lckr-jupyterlab-variableinspector
    - jupyterlab-spellchecker
