name: EHML
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - matplotlib
  - pandas
  - jupyter
  - jupyterlab
  - seaborn
  - pip
  - ipywidgets
  - scikit-learn
  - pip:
    - openpyxl
    - numpy
    - transformers
    - pytorch-lightning
    - 'lightning-flash[tabular,text,image]'
    - plotly
    - lckr-jupyterlab-variableinspector
    - jupyterlab-spellchecker
